on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: Build 🔧 & Test 🔧
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Setup Valgrind
      run: sudo apt install -y valgrind

    - name: Build 🔧 test/calculate.c
      run: gcc -g ./include/**.c ./test/calculate.c -o ./calculate.out

    - name: Leak Test 🔧 with valgrind ./calculate.out
      run: valgrind --leak-check=full ./calculate.out
