on:
  workflow_dispatch:
  push:
jobs:
  build-and-test:
    name: Build 🔧 & Test 🔧
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Setup Valgrind
      run: sudo apt install -y valgrind

    - name: Build 🔧 => ./a.out
      run: gcc -g -include ./include/**.h ./include/**.c -include test/*.h test/*.c -o ./a.out

    - name: Leak Test 🔧 with valgrind ./a.out
      run: valgrind --leak-check=full ./a.out
